Homework 1
================
Qianhui Xu

# Problem 1

## Create a data frame with the specified elements.

``` r
prob1_df = 
  tibble(
   samp_numeric = rnorm(10),
   samp_logical = samp_numeric > 0,
   char_vec = c("A", "A", "B", "B", "A", "C", "B", "C", "C", "A"),
  factor_vec = factor(c("high", "high", "mid", "mid", "high", "low", "mid", "low", "low", "high"))
  )
```

## Means

``` r
mean(pull(prob1_df,samp_numeric))
```

    ## [1] -0.09836418

``` r
mean(pull(prob1_df, samp_logical))
```

    ## [1] 0.4

``` r
mean(pull(prob1_df, char_vec))
```

    ## Warning in mean.default(pull(prob1_df, char_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(prob1_df, factor_vec))
```

    ## Warning in mean.default(pull(prob1_df, factor_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

## What works and what doesn’t?

Take the mean of each variable in my data frame.I found that we could
obtain the means for numeric and logical variables. However, we could
not obtain the means for character variable, and factor variable.

\#Convert

``` r
as.numeric(pull(prob1_df, samp_logical))
as.numeric(pull(prob1_df, char_vec))
as.numeric(pull(prob1_df, factor_vec))
```

## What happens and why?

The logical variable and factor variable can be converted to numeric
variables. It’ because the logical variables could be stored as 0
(FALSE) and 1 (TRUE). Therefore, the “FALSE” could be converted to 0 and
“TRUE” could be converted to 1.

For factor variables, the elements could be converted to the numeric
codes that correspond to the factor levels.(in our sample, we have 3
levels) Because factor vector contains and stores a set of numeric codes
with character-valued levels.

However, the character variable could not be converted to numeric
variable.Because character variable contains characters, which could not
be converted to numeric values.

Yes, this could help me to explain what happens when I try to make the
mean. Because numeric and logical variables are stored as numeric
values.We could therefore obtain their mean values. However, the factor
variables could be converted to numeric variables but after the
convertion, we could not obtain the mean value before convertion. The
character variables contains characters and we could not obtain the mean
from it.

## Problem1,second code chunk

``` r
as.numeric(pull(prob1_df, samp_logical)) * pull(prob1_df, samp_numeric)
```

    ##  [1] 0.8338618 0.0000000 0.6163267 0.2744267 0.3790213 0.0000000 0.0000000
    ##  [8] 0.0000000 0.0000000 0.0000000

``` r
as.factor(pull(prob1_df, samp_logical)) * pull(prob1_df, samp_numeric)
```

    ## Warning in Ops.factor(as.factor(pull(prob1_df, samp_logical)), pull(prob1_df, :
    ## '*' not meaningful for factors

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(as.factor(pull(prob1_df, samp_logical))) * pull(prob1_df, samp_numeric)
```

    ##  [1]  1.66772360 -0.23634595  1.23265349  0.54885342  0.75804263 -0.83532358
    ##  [7] -0.65621813 -0.76541849 -0.01464502 -0.57932718

# Problem 2

``` r
data("penguins", package = "palmerpenguins")
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

## Discription of the dataset

The variable names are: species, island, bill\_length\_mm,
bill\_depth\_mm, flipper\_length\_mm, body\_mass\_g, sex, year

The median of the body mass is 4050, the range for bill depth is13.1,
21.5.the range for bill length is32.1, 59.6. The penguins are from 3
islands. The names of each island are Biscoe, Dream, Torgersen.There are
3 penguin species. The names of each species are Adelie, Chinstrap,
Gentoo.

There are 344rows and 8columns in this dataset, and The size of the
dataset is 2752.

The mean flipper length is 200.9152047 mm.

## Scatterplot and save

``` r
#create scatterplot and related labels

ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point() + ggtitle("Scatter plot")
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](P8105_hw01_q2199_files/figure-gfm/scatterplot_penguins-1.png)<!-- -->

``` r
#save and export the scatter plot

ggsave("scatterplot_penguins.pdf", height = 4, width = 4) 
```

    ## Warning: Removed 2 rows containing missing values (geom_point).
